[build]
  publish = "build"
  command = "npm run build"

[functions]
  directory = "netlify/functions"

[[functions]]
  schedule = "0 * * * *" # Every hour
  path = "/.netlify/functions/refreshSpotifyToken"