[build]
  publish = "build" # React's default build directory
  command = "npm run build" # Command to build the React app

[functions]
  directory = "netlify/functions" # Path to your functions directory

[[functions]]
  schedule = "0 * * * *"
  path = "/.netlify/functions/refreshSpotifyToken"