[build]
  publish = "build"
  command = "npm run build"

[functions]
  directory = "netlify/functions" # The directory where your functions are stored

[[scheduled.functions]]
  path = "/.netlify/functions/refreshSpotifyToken"
  schedule = "0 * * * *" # Run every hour